### ISSUE TITLE
"Lost connection to MySQL server during query" error occurred when use two source tags

### ISSUE THREAD

**Issue by kakakakakku** [kenjiskywalker/fluent-plugin-rds-slowlog#16]
Hi ! Thank you for good plugin !

When I use two `source` tags for another RDS Instance ( like Aurora Writer & Aurora Reader ), an error occurred. If I tried using one `source` tag, it worked good.

This is sample config.

```
<source>
    @type rds_slowlog
    tag rds_slowlog.writer
    host example1.ap-northeast-1.rds.amazonaws.com
    username xxx
    password yyy
    interval 300
</source>

<source>
    @type rds_slowlog
    tag rds_slowlog.reader
    host example2.ap-northeast-1.rds.amazonaws.com
    username xxx
    password yyy
    interval 300
</source>

<match rds_slowlog.*>
    ...
</match>
```

This is error ( stack trace ).

```
2017-02-22 15:35:12 +0900 [error]: Lost connection to MySQL server during query
  2017-02-22 15:35:12 +0900 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/mysql2-0.3.21/lib/mysql2/client.rb:80:in `_query'
  2017-02-22 15:35:12 +0900 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/mysql2-0.3.21/lib/mysql2/client.rb:80:in `block in query'
  2017-02-22 15:35:12 +0900 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/mysql2-0.3.21/lib/mysql2/client.rb:79:in `handle_interrupt'
  2017-02-22 15:35:12 +0900 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/mysql2-0.3.21/lib/mysql2/client.rb:79:in `query'
  2017-02-22 15:35:12 +0900 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-rds-slowlog-0.0.7/lib/fluent/plugin/in_rds_slowlog.rb:69:in `output'
  2017-02-22 15:35:12 +0900 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-rds-slowlog-0.0.7/lib/fluent/plugin/in_rds_slowlog.rb:92:in `call'
  2017-02-22 15:35:12 +0900 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-rds-slowlog-0.0.7/lib/fluent/plugin/in_rds_slowlog.rb:92:in `on_timer'
  2017-02-22 15:35:12 +0900 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/cool.io-1.4.2/lib/cool.io/loop.rb:88:in `run_once'
  2017-02-22 15:35:12 +0900 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/cool.io-1.4.2/lib/cool.io/loop.rb:88:in `run'
  2017-02-22 15:35:12 +0900 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-rds-slowlog-0.0.7/lib/fluent/plugin/in_rds_slowlog.rb:62:in `watch'
2017-02-22 15:45:22 +0900 [error]: MySQL server has gone away
  2017-02-22 15:45:22 +0900 [error]: suppressed same stacktrace
2017-02-22 15:55:32 +0900 [error]: closed MySQL connection
  2017-02-22 15:55:32 +0900 [error]: suppressed same stacktrace
```

I tried setting other `interval` between two `source` tags like below, the same error occurred when the intervals overlapped.

```
<source>
    ...
    interval 300
</source>

<source>
    ...
    interval 610
</source>
```

# Question

@kenjiskywalker 
Do you have any ideas ?
Is this my fault ?
Please give me advice 🙏 

# Specs

- td-agent 0.12.20
- fluent-plugin-rds-slowlog 0.0.7
- RDS (Amazon Aurora)

Thank you 👍

**Comment by kakakakakku** [comment]
# Additional information

Today, I tried `fluent-plugin-rds-slowlog 0.0.8` ( this is unreleased version like below ), but same error occured.

- https://github.com/kenjiskywalker/fluent-plugin-rds-slowlog/pull/12
- https://github.com/kenjiskywalker/fluent-plugin-rds-slowlog/pull/14

**Comment by winebarrel** [comment]
v0.0.8 has been released.

**Comment by kakakakakku** [comment]
@winebarrel 
Thanks 🙏
